<?php

// This file has been auto-generated by the Symfony Dependency Injection Component
// You can reference it in the "opcache.preload" php.ini setting on PHP >= 7.4 when preloading is desired

use Symfony\Component\DependencyInjection\Dumper\Preloader;

require dirname(__DIR__, 3).'\\vendor/autoload.php';
require __DIR__.'/ContainerDDe5gRx/Kematjaya_Tests_Currency_KmjCurrencyTestingKernelTestDebugContainer.php';

$classes = [];
$classes[] = 'Kematjaya\Currency\KmjCurrencyBundle';
$classes[] = 'Symfony\Component\DependencyInjection\ContainerInterface';

Preloader::preload($classes);
