<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXCa5hO8\Kematjaya_Tests_Currency_KmjCurrencyTestingKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXCa5hO8/Kematjaya_Tests_Currency_KmjCurrencyTestingKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerXCa5hO8.legacy');

    return;
}

if (!\class_exists(Kematjaya_Tests_Currency_KmjCurrencyTestingKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerXCa5hO8\Kematjaya_Tests_Currency_KmjCurrencyTestingKernelTestDebugContainer::class, Kematjaya_Tests_Currency_KmjCurrencyTestingKernelTestDebugContainer::class, false);
}

return new \ContainerXCa5hO8\Kematjaya_Tests_Currency_KmjCurrencyTestingKernelTestDebugContainer([
    'container.build_hash' => 'XCa5hO8',
    'container.build_id' => '8aed5034',
    'container.build_time' => 1587522125,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXCa5hO8');
