<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerC6VIc0Z\Kematjaya_Tests_Currency_KmjCurrencyTestingKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerC6VIc0Z/Kematjaya_Tests_Currency_KmjCurrencyTestingKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerC6VIc0Z.legacy');

    return;
}

if (!\class_exists(Kematjaya_Tests_Currency_KmjCurrencyTestingKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerC6VIc0Z\Kematjaya_Tests_Currency_KmjCurrencyTestingKernelTestDebugContainer::class, Kematjaya_Tests_Currency_KmjCurrencyTestingKernelTestDebugContainer::class, false);
}

return new \ContainerC6VIc0Z\Kematjaya_Tests_Currency_KmjCurrencyTestingKernelTestDebugContainer([
    'container.build_hash' => 'C6VIc0Z',
    'container.build_id' => '1d032f78',
    'container.build_time' => 1587205784,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerC6VIc0Z');
