<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDDe5gRx\Kematjaya_Tests_Currency_KmjCurrencyTestingKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDDe5gRx/Kematjaya_Tests_Currency_KmjCurrencyTestingKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerDDe5gRx.legacy');

    return;
}

if (!\class_exists(Kematjaya_Tests_Currency_KmjCurrencyTestingKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerDDe5gRx\Kematjaya_Tests_Currency_KmjCurrencyTestingKernelTestDebugContainer::class, Kematjaya_Tests_Currency_KmjCurrencyTestingKernelTestDebugContainer::class, false);
}

return new \ContainerDDe5gRx\Kematjaya_Tests_Currency_KmjCurrencyTestingKernelTestDebugContainer([
    'container.build_hash' => 'DDe5gRx',
    'container.build_id' => 'dddb9c63',
    'container.build_time' => 1587199559,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDDe5gRx');
